import {
  ClearSkyIcon,
  OvercastIcon,
  PartyCloudyDrizzleIcon,
  PartyCloudyFreezingFogIcon,
  PartyCloudyHaze,
  PartyCloudyRain,
  PartyCloudyShower,
  PartyCloudySleet,
  PartyCloudySmoke,
  PartyCloudySnowShower,
  PartyCloudySnow,
  ThunderstormHailIcon,
  ThunderstormRainIcon,
  UnknownIcon
} from '../components/Icons'

const iconMap = {
  200: ThunderstormRainIcon,
  201: ThunderstormRainIcon,
  202: ThunderstormRainIcon,
  230: PartyCloudyDrizzleIcon,
  231: PartyCloudyDrizzleIcon,
  232: PartyCloudyDrizzleIcon,
  233: PartyCloudyDrizzleIcon,
  300: ThunderstormHailIcon,
  301: ThunderstormHailIcon,
  302: ThunderstormHailIcon,
  500: PartyCloudyRain,
  501: PartyCloudyRain,
  502: PartyCloudyRain,
  511: PartyCloudyRain,
  520: PartyCloudyShower,
  521: PartyCloudyShower,
  522: PartyCloudyShower,
  600: PartyCloudySnow,
  601: PartyCloudySnow,
  602: PartyCloudySnow,
  610: PartyCloudySleet,
  611: PartyCloudySleet,
  612: PartyCloudySleet,
  621: PartyCloudySnowShower,
  622: PartyCloudySnowShower,
  623: PartyCloudySnowShower,
  700: PartyCloudyHaze,
  721: PartyCloudyHaze,
  741: PartyCloudyHaze,
  711: PartyCloudySmoke,
  731: PartyCloudySmoke,
  751: PartyCloudyFreezingFogIcon,
  800: ClearSkyIcon,
  801: OvercastIcon,
  802: OvercastIcon,
  803: OvercastIcon,
  804: OvercastIcon,
  900: UnknownIcon
}

export default iconMap
